pipeline {
    agent any
    stages {
        stage('Build Angular') {
            steps {
                sh 'docker run --rm -v $PWD:/app -w /app node:20 npm install'
                sh 'docker run --rm -v $PWD:/app -w /app node:20 npm run build --prod'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-angular-app .'
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'docker tag my-angular-app:latest <dockerhub-username>/my-angular-app:latest'
                sh 'docker push <dockerhub-username>/my-angular-app:latest'
            }
        }
    }
}
