pipeline {
    agent any
    tools {
        nodejs "Node16"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-pat-angular',
                    url: 'https://github.com/sonalic163/employee-project.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build Angular') {
            steps {
                sh 'npm run build --prod'
            }
        }
    }
}
